### ISSUE TITLE
Utilizar PascalCase para el nombre de las clases

### ISSUE THREAD

**Issue by delucas** [LosCacheFC/jrpg#11]
En el proyecto hay clases que no cumplen con la nomenclatura esperada.
Por favor, corríjanlas. Ejemplos:

![image](https://cloud.githubusercontent.com/assets/684051/19831374/b7e0e57c-9dde-11e6-8e43-44442427601d.png)

Evitar los guiones bajos.

**Comment by ruttimannh** [comment]
Ya están actualizados los nombres de las clases
