### ISSUE TITLE
Formato de los CA

### ISSUE THREAD

**Issue by delucas** [LosCacheFC/jrpg#5]
Los [Criterios de Aceptación](https://github.com/LosCacheFC/jrpg/commit/c68551a5b22c71bf626bb5a6e327e03d95e54fca) deberían cumplir con la norma estipulada: G-W-T

Corregir conforme [esta regla](https://github.com/programacion-avanzada/notas/wiki/Historias-de-Usuario-y-Criterios-de-Aceptaci%C3%B3n).

**Comment by delucas** [comment]
Este issue lleva una semana

**Comment by NicoVespoli** [comment]
Listo profe! Me habia olvidado de cerrar el issue
