### ISSUE TITLE
Sobre los main

### ISSUE THREAD

**Issue by delucas** [LosCacheFC/jrpg#7]
![giphy 1](https://cloud.githubusercontent.com/assets/684051/19620453/227e5a6c-9854-11e6-97d9-14f9ee6d5b31.gif)

¡SACRILEGIO!

No hay que utilizar `main` dentro de ningún proyecto. Para ello, utilicen tests de JUnit.
Eliminen todos los del proyecto, [por ejemplo este](https://github.com/LosCacheFC/jrpg/blob/master/dominio/src/main/java/dominio/Personaje.java#L562).

**Comment by NicoVespoli** [comment]
main eliminado!
