### ISSUE TITLE
Sobre las HU

### ISSUE THREAD

**Issue by delucas** [LosCacheFC/jrpg#8]
Tienen dos directorios para Historias de Usuario, unifiquen todo en uno solo, que es el que no posee los %20 en lugar de espacios. Es decir, pongan todo en `historias de usuario`

**Comment by NicoVespoli** [comment]
Listo profe! Nose porque pero me creaba esa carpeta cada vez que ponia las HU en la otra carpeta, creo que ya se soluciono

**Comment by delucas** [comment]
:+1:
